[package]
name = "foo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7" # for debug, can remove for release # TODO make [profile.debug] or whatever
console_log = "1.0.0"              # for debug, can remove for release
js-sys = "0.3.83"
log = "0.4.29"                     # for debug, can remove for release
wasm-bindgen = "0.2.106"
web-sys = { version = "0.3.83", features = [
    "Window",
    "WebGl2RenderingContext",
    "WebGlBuffer",
    "WebGlFramebuffer",
    "WebGlProgram",
    "WebGlShader",
    "WebGlTexture",
    "WebGlUniformLocation",
    "WebGlVertexArrayObject",
    "XrViewport",
] }
wee_alloc = "0.4.5"

[profile.release]
lto = "fat"   # Or "fat" for more aggressive optimizations
opt-level = "z"  # Optimize for size
# panic = "abort"  # Reduce panic code size
panic = "unwind"
strip = "symbols"   # Strip symbols from binary*

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]
